# Generated by Django 4.1 on 2022-09-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='age',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='breed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='env_cats',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='env_child',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='env_dogs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='org_city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='org_email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='org_mission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='org_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='org_phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='org_state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='org_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='photos',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='shots',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='sterile',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
